// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIvMLMtuLF_pAAuZdI_p5eHEuqJOxGHI',
    appId: '1:243769216237:web:889e385ce69d21a1bc50e4',
    messagingSenderId: '243769216237',
    projectId: 'sustainabit-c2211',
    authDomain: 'sustainabit-c2211.firebaseapp.com',
    storageBucket: 'sustainabit-c2211.firebasestorage.app',
    measurementId: 'G-CKS3E85J9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGMbJAHn9l24P53uU98-7rox5WURd6xI',
    appId: '1:243769216237:android:7a5247cfbadafae2bc50e4',
    messagingSenderId: '243769216237',
    projectId: 'sustainabit-c2211',
    storageBucket: 'sustainabit-c2211.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuIygjAIvgaqAYk1KEVBofMQU-LL3zldo',
    appId: '1:243769216237:ios:1b7d7b418884d7bdbc50e4',
    messagingSenderId: '243769216237',
    projectId: 'sustainabit-c2211',
    storageBucket: 'sustainabit-c2211.firebasestorage.app',
    iosClientId: '243769216237-563gjj79benap7j36unkquptc51spnv6.apps.googleusercontent.com',
    iosBundleId: 'com.sustai',
  );
}
